#!/usr/bin/env bash -e
# Deploy to Bintray

cd "$(dirname "$0")"/..

# Version number
[[ "$#" -ne 1 ]] && { echo "Usage: $ deploy <a.b.c>"; exit 1; }
VERSION="$1"

# Env vars
[ -z "$BINTRAY_USER" ] && { echo "Missing env var BINTRAY_USER"; exit 1; }
[ -z "$BINTRAY_KEY" ]  && { echo "Missing env var BINTRAY_KEY"; exit 1; }
URL="https://$BINTRAY_USER:$BINTRAY_KEY@api.bintray.com"

# Check git status
[ -n "$(git status --porcelain)" ] && { echo "Unclean repo"; exit 1; }

# Create version
curl -s -X POST "$URL/packages/appstax/maven/appstax-java/versions" \
-H "Content-Type:application/json" \
-d "{\"name\":\"$VERSION\"}" > /dev/null

# Deploy release
mvn -s settings.xml --batch-mode -Dtag="v$VERSION" -DreleaseVersion="$VERSION" release:prepare
mvn -s settings.xml release:perform

# Publish release
curl -s -X POST "$URL/content/appstax/maven/appstax-java/$VERSION/publish" > /dev/null

# Push release commits
git push