#!/usr/bin/env bash -eu
# Temporary local "deploy"

cd "$(dirname "$0")"/..

FILE="appstax-java-1.0.0.jar"
SOURCE="target/$FILE"
TARGET="../appstax-android/appstax/libs/$FILE"

mvn package
rm -f "$TARGET"
cp "$SOURCE" "$TARGET"
