#!/usr/bin/env bash -eu
# Release to Bintray

cd "$(dirname "$0")"/..

# Config
VERSION=$(mvn help:evaluate -Dexpression=project.version | grep -v "^\[" | sed 's/-.*//')
BINTRAY="https://$BINTRAY_USER:$BINTRAY_KEY@api.bintray.com"

# Confirmation
read -p "Publish version $VERSION? [y/n] " reply
case $reply in
    y) echo "Publishing...";;
    *) exit 1 ;;
esac

# Check git status
[ -n "$(git status --porcelain)" ] && { echo "Unclean repo"; exit 1; }

# Create version
curl -s -X POST "$BINTRAY/packages/appstax/maven/appstax-java/versions" \
-H "Content-Type:application/json" \
-d "{\"name\":\"$VERSION\"}" > /dev/null

# Deploy release
mvn -s settings.xml --batch-mode -Dtag="v$VERSION" -DreleaseVersion="$VERSION" release:prepare
mvn -s settings.xml release:perform

# Publish release
curl -s -X POST "$BINTRAY/content/appstax/maven/appstax-java/$VERSION/publish" > /dev/null

# Push release commits
git push